on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: hugo --minify
    - name: Deploy
      run: apt-get -yqq install lftp && lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }}" "$FTP_SERVER" -e "mirror -e -R -p public/ . ; quit"
